/*
 * This source file was generated by the Gradle 'init' task
 */
package org.APCSLowell;

public class GoogleBillboard {
    public boolean isPrime(long n) {
        if(num < 2)
    return false;
  for(int i = 2; i <= Math.sqrt(num); i++)
    if(num % i == 0)
      return false;
  return true;
        return false;
    }
    public long firstPrimeNumberIn(String n) {
        // Write your code here.
        return -1;
    }
}
